press ("GUI r")
delay (500)
type ("cmd")
delay (500)
press ("ENTER")
delay (500)
type ("start https://www.youtube.com/watch?v=6n3pFFPSlW4")
delay (500)
press ("ENTER")
delay (50)
type ("exit")
delay (50)
press ("ENTER")